version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "3000:80"
    networks:
      - frontend
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    networks:
      - backend
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    networks:
      - backend

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.17.0.0/16
          gateway: 172.17.0.1
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

volumes:
  db_data: